"""empty message

Revision ID: 159f893c9ddd
Revises: a6bb9e7566d5
Create Date: 2024-08-22 21:17:47.897637

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "159f893c9ddd"
down_revision: Union[str, None] = "a6bb9e7566d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
