"""empty message

Revision ID: 7e5fe9fa88b9
Revises: 2688e40d0795
Create Date: 2024-08-22 22:29:11.474065

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7e5fe9fa88b9"
down_revision: Union[str, None] = "2688e40d0795"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
