"""empty message

Revision ID: a6bb9e7566d5
Revises: c19057503977
Create Date: 2024-08-22 12:12:27.505700

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a6bb9e7566d5"
down_revision: Union[str, None] = "c19057503977"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
