"""empty message

Revision ID: c19057503977
Revises: bf9edf502be0
Create Date: 2024-08-22 12:11:48.523817

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c19057503977"
down_revision: Union[str, None] = "bf9edf502be0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
